[pytest]
pythonpath = .
asyncio_mode = auto
addopts = -n auto --basetemp=.pytest_tmp
markers =
    unit: Standard unit test marker
    integration: Integration test marker
    slow: Slow test marker
filterwarnings =
    ignore:.*_UnionGenericAlias.*:DeprecationWarning:google\.genai.*
