# Exported from Render on 2025-08-16T08:02:38Z
services:
- type: web
  name: gemaibotv2
  runtime: docker
  repo: https://github.com/Le-Who/gemaibotv2
  plan: free
  envVars:
  - key: LOG_JSON
    sync: false
  - key: REDIS_URL
    sync: false
  - key: ENABLE_PERSISTENT_QUEUE
    sync: false
  - key: TAVILY_API_KEYS
    sync: false
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: GEMINI_API_KEYS
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: ADMIN_ID
    sync: false
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: "off"
version: "1"
