import asyncio

from app.providers.tts import generate_speech


async def main():
    pcm = await generate_speech("Тестовый чанк номер один", "FAKE_KEY", tts_temperature=0.8)
    print(f"Generated bytes: {len(pcm) if pcm else 'None'}")


asyncio.run(main())
