apiVersion: 1

datasources:
  - name: YT-DLP Bot Logs
    uid: ytdlbot-loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
    timeout: 10
    jsonData:
      maxLines: 100
      timeout: 10
      derivedFields:
        - name: request_id
          matcherRegex: '"request_id":"([a-f0-9]{32})"'
          url: '/explore?left={"datasource":"ytdlbot-loki","queries":[{"refId":"A","expr":"{service_name=\\"ytdlbot\\"} | json | request_id=\\"${__value.raw}\\""}],"range":{"from":"now-15m","to":"now"}}'
          urlDisplayLabel: Find this request
        - name: trace_id
          matcherRegex: '"trace_id":"([a-f0-9]{32})"'
          url: '/explore?left={"datasource":"ytdlbot-loki","queries":[{"refId":"A","expr":"{service_name=\\"ytdlbot\\"} | json | trace_id=\\"${__value.raw}\\""}],"range":{"from":"now-15m","to":"now"}}'
          urlDisplayLabel: Find this trace
